spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
management:
  health:
    defaults:
      enabled: false

shenyu:
    sync:
        websocket:
            urls: ws://localhost:9095/websocket
